// $ otool -L /System/Library/CoreServices/Finder.app/Contents/MacOS/Finder
// $ class-dump /System/Library/PrivateFrameworks/DesktopServicesPriv.framework/Versions/A/DesktopServicesPriv

/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#pragma mark Named Structures

struct TChildrenList;

/*struct TCountedPtr<TFSInfo> {
    struct TFSInfo *_field1;
};

struct TCountedPtr<TFSVolumeInfo> {
    struct TFSVolumeInfo *_field1;
};*/

struct TFSInfo;

struct TFSVolumeInfo;

/*struct TNode {
    int _field1;
    struct TNode *_field2;
    struct TCountedPtr<TFSVolumeInfo> _field3;
    int _field4;
    struct TCountedPtr<TFSInfo> _field5;
    struct TChildrenList *_field6;
    struct TNodePtr _field7;
    void *_field8;
    struct TNotifierList *_field9;
    struct TOperationLock *_field10;
    unsigned char _field11;
    unsigned int :1;
    unsigned int :1;
    unsigned int :1;
};*/

struct TNodePtr {
    struct TNode *_field1;
};

struct TNotifierList;

struct TOperationLock;

#pragma mark -

/*
 * File: /System/Library/PrivateFrameworks/DesktopServicesPriv.framework/Versions/A/DesktopServicesPriv
 * UUID: 6B83172E-F539-3AF8-A76D-1F9EA357B076
 * Arch: Intel x86-64 (x86_64)
 *       Current version: 625.1.9, Compatibility version: 1.0.0
 *       Minimum Mac OS X version: 10.7.0
 *
 *       Objective-C Garbage Collection: Supported
 */

@protocol FINode <NSObject, NSCopying>
+ (id)nodeFromNodeRef:(struct OpaqueNodeRef *)arg1;
- (struct OpaqueNodeRef *)nodeRef;
@end

/*@protocol NSCopying
- (id)copyWithZone:(struct _NSZone *)arg1;
@end

@protocol NSObject
- (id)description;
- (unsigned long long)retainCount;
- (id)autorelease;
- (oneway void)release;
- (id)retain;
- (BOOL)respondsToSelector:(SEL)arg1;
- (BOOL)conformsToProtocol:(id)arg1;
- (BOOL)isMemberOfClass:(Class)arg1;
- (BOOL)isKindOfClass:(Class)arg1;
- (BOOL)isProxy;
- (id)performSelector:(SEL)arg1 withObject:(id)arg2 withObject:(id)arg3;
- (id)performSelector:(SEL)arg1 withObject:(id)arg2;
- (id)performSelector:(SEL)arg1;
- (struct _NSZone *)zone;
- (id)self;
- (Class)class;
- (Class)superclass;
- (unsigned long long)hash;
- (BOOL)isEqual:(id)arg1;
@end*/

@interface FINode : NSObject <FINode>
{
    char _node[88];
}

+ (id)nodeFromNodeRef:(struct OpaqueNodeRef *)arg1;
- (struct OpaqueNodeRef *)nodeRef;
- (id)description;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)mutableCopy;
- (oneway void)release;
- (oneway void)releaseUnderMonitor;
- (id)retain;
- (struct TNode *)asTNode;
- (void)finalize;
- (void)dealloc;
- (id)init;
- (void)deleteTNode;

@end
