/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <Cocoa/Cocoa.h>

@class CALayer;

@interface TDesktopLayer : NSObject
{
    id <TDesktopLayerDelegate> _delegate;
    struct CGRect _frame;
    CALayer *_layer;
}

+ (id)overlayRootLayer;
+ (id)hostLayerForLevel:(int)arg1;
+ (id)rootLayer;
+ (void)setRootLayer:(id)arg1;
@property(nonatomic) struct CGRect frame; // @synthesize frame=_frame;
//@property(nonatomic) id <TDesktopLayerDelegate> delegate; // @synthesize delegate=_delegate;
//- (id).cxx_construct;
//- (void).cxx_destruct;
- (void)orderBelow:(id)arg1;
- (void)orderAbove:(id)arg1;
- (void)orderFront;
- (void)hide;
- (void)show;
- (void)drawLayer:(id)arg1 inContext:(struct CGContext *)arg2;
- (void)setNeedsDisplay;
- (id)caLayer;
- (void)dealloc;
- (id)init;
- (id)initWithLevel:(int)arg1;

@end

