/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "PFImageKit.h"

//@class IKImageWrapper;

@interface TIconViewCell : IKImageBrowserCell
{
    IKImageWrapper *_titleImage;
    BOOL _twoLine;
    //CDStruct_b8373011 _titleSettings;
}

+ (struct CGSize)cellSizeForIconSize:(double)arg1 labelOnBottom:(BOOL)arg2 gridSpacing:(double)arg3 titleAttrs:(id)arg4 subTitleAttrs:(id)arg5;
//- (id).cxx_construct;
//- (void).cxx_destruct;
- (void)drawTitle;
- (void)invalidate;
- (id)titleImage;
//- (BOOL)titleImageStillValid:(CDStruct_b8373011)arg1;
//- (CDStruct_b8373011)currentTitleImageSettings;
- (id)constructTitleImage;
- (void)drawLabel:(struct CGContext *)arg1 fillRect:(struct CGRect)arg2 bounds:(struct CGRect)arg3 firstLine:(struct CGRect)arg4 secondLine:(struct CGRect)arg5 actualLineCount:(unsigned long long)arg6 selected:(BOOL)arg7 labelValue:(short)arg8 justification:(short)arg9 inset:(double)arg10 radius:(double)arg11;
//- (CDStruct_51b97681)calculateTextMetrics:(id)arg1 attributes:(id)arg2;
- (struct CGRect)placeSubString:(id)arg1 atIndex:(unsigned long long)arg2 fromFrame:(struct CGRect)arg3 bounds:(struct CGRect)arg4 attributes:(id)arg5 lineBreakMode:(unsigned long long)arg6 position:(BOOL)arg7;
- (id)subString:(id)arg1 atIndex:(unsigned long long)arg2 attributes:(id)arg3 lineBreakMode:(unsigned long long)arg4;
- (int)heightOfInfoSpace;
- (struct CGRect)subtitleFrame;
- (struct CGRect)titleFrame;
- (double)maxTitleWidth;
- (double)titleOffset;
- (struct CGRect)imageFrame;
- (struct CGRect)frame;
- (double)endCapWidth;
- (BOOL)showItemInfo;
- (BOOL)showPreview;
- (BOOL)labelOnBottom;
- (double)iconSize;
- (void)dealloc;
- (id)init;

@end

