/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "TIconAndTextWithActionCell.h"
#import "CDStructures.h"

@interface TNodeIconAndNameCell : TIconAndTextWithActionCell
{
    struct TFENode _node;
}

//- (id).cxx_construct;
//- (void).cxx_destruct;
- (BOOL)accessibilityIsAttributeSettable:(id)arg1;
- (id)accessibilityAttributeValue:(id)arg1;
- (id)accessibilityAttributeNames;
- (void)setNode:(const struct TFENode *)arg1;
- (const struct TFENode *)node;
- (id)copyWithZone:(struct _NSZone *)arg1;

@end

